# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FRPStarterDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FRPStarterDemo
pod 'ReactiveCocoa', '~> 1.0.0-alpha.4'
pod 'ReactiveSwift', '~> 5.0.0-alpha.3'

end
